import { joinIfNextIsLowerCase } from '../joinIfNextIsLowerCase'

describe('check if corrects splitted array', () => {
    test('', () => {
        const joined = ['Urodziłam się w 2000r. i mam trzech braci', 'Moja matka nazywa się Grażyna', 'Lubi oglądać telewizję, np. programy o domach', 'Jest fajna, urodziła się w 1955r. w Polsce'];
        expect(joinIfNextIsLowerCase(['Urodziłam się w 2000r', 'i mam trzech braci', 'Moja matka nazywa się Grażyna', 'Lubi oglądać telewizję, np', 'programy o domach', 'Jest fajna, urodziła się w 1955r', 'w Polsce', ""])).toEqual(joined);
    });
    test('', () => {
        const joined = ["ROZPORZĄDZENIE PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679\n\nz dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)\n\n(Tekst mający znaczenie dla EOG)\n\nPARLAMENT EUROPEJSKI I RADA UNII EUROPEJSKIEJ,\n\nuwzględniając Traktat o funkcjonowaniu Unii Europejskiej, w szczególności jego art. 16,\n\nuwzględniając wniosek Komisji Europejskiej,\n\npo przekazaniu projektu aktu ustawodawczego parlamentom narodowym,\n\nuwzględniając opinię Europejskiego Komitetu Ekonomiczno-Społecznego (1),\n\nuwzględniając opinię Komitetu Regionów (2),\n\nstanowiąc zgodnie ze zwykłą procedurą ustawodawczą (3),\n\na także mając na uwadze, co następuje:\n\n(1)\n\nOchrona osób fizycznych w związku z przetwarzaniem danych osobowych jest jednym z praw podstawowych", "Art. 8 ust. 1 Karty praw podstawowych Unii Europejskiej (zwanej dalej „Kartą praw podstawowych”) oraz art. 16 ust. 1 Traktatu o funkcjonowaniu Unii Europejskiej (TFUE) stanowią, że każda osoba ma prawo do ochrony danych osobowych jej dotyczących", "(2)\n\nZasady i przepisy dotyczące ochrony osób fizycznych w związku z przetwarzaniem ich danych osobowych nie mogą – niezależnie od obywatelstwa czy miejsca zamieszkania takich osób – naruszać ich podstawowych praw i wolności, w szczególności prawa do ochrony danych osobowych", "Niniejsze rozporządzenie ma na celu przyczyniać się do tworzenia przestrzeni wolności, bezpieczeństwa i sprawiedliwości oraz unii gospodarczej, do postępu społeczno-gospodarczego, do wzmacniania i konwergencji gospodarek na rynku wewnętrznym, a także do pomyślności ludzi"];
        expect(joinIfNextIsLowerCase(["ROZPORZĄDZENIE PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679\n\nz dnia 27 kwietnia 2016 r", "w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)\n\n(Tekst mający znaczenie dla EOG)\n\nPARLAMENT EUROPEJSKI I RADA UNII EUROPEJSKIEJ,\n\nuwzględniając Traktat o funkcjonowaniu Unii Europejskiej, w szczególności jego art", "16,\n\nuwzględniając wniosek Komisji Europejskiej,\n\npo przekazaniu projektu aktu ustawodawczego parlamentom narodowym,\n\nuwzględniając opinię Europejskiego Komitetu Ekonomiczno-Społecznego (1),\n\nuwzględniając opinię Komitetu Regionów (2),\n\nstanowiąc zgodnie ze zwykłą procedurą ustawodawczą (3),\n\na także mając na uwadze, co następuje:\n\n(1)\n\nOchrona osób fizycznych w związku z przetwarzaniem danych osobowych jest jednym z praw podstawowych", "Art", "8 ust", "1 Karty praw podstawowych Unii Europejskiej (zwanej dalej „Kartą praw podstawowych”) oraz art", "16 ust", "1 Traktatu o funkcjonowaniu Unii Europejskiej (TFUE) stanowią, że każda osoba ma prawo do ochrony danych osobowych jej dotyczących", "(2)\n\nZasady i przepisy dotyczące ochrony osób fizycznych w związku z przetwarzaniem ich danych osobowych nie mogą – niezależnie od obywatelstwa czy miejsca zamieszkania takich osób – naruszać ich podstawowych praw i wolności, w szczególności prawa do ochrony danych osobowych", "Niniejsze rozporządzenie ma na celu przyczyniać się do tworzenia przestrzeni wolności, bezpieczeństwa i sprawiedliwości oraz unii gospodarczej, do postępu społeczno-gospodarczego, do wzmacniania i konwergencji gospodarek na rynku wewnętrznym, a także do pomyślności ludzi"])).toEqual(joined);
    });
}) 