import { joinIfNextIsLowerCase } from '../joinIfNextIsLowerCase';


describe('check if corrects splitted array', () => {
    test('short array', () => {
        const joined = ['Urodziłam się w 2000r. i mam trzech braci', 'Moja matka nazywa się Grażyna', 'Lubi oglądać telewizję, np. programy o domach', 'Jest fajna, urodziła się w 1955r. w Polsce, a w 2006r. przeprowadziła się do Włoch'];
        expect(joinIfNextIsLowerCase(['Urodziłam się w 2000r', 'i mam trzech braci', 'Moja matka nazywa się Grażyna', 'Lubi oglądać telewizję, np', 'programy o domach', 'Jest fajna, urodziła się w 1955r', 'w Polsce, a w 2006r', "przeprowadziła się do Włoch"])).toEqual(joined);
    });
    test('long array', () => {
        const joined = ['ROZPORZĄDZENIE PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679\n\nz dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)\n\n(Tekst mający znaczenie dla EOG)\n\nPARLAMENT EUROPEJSKI I RADA UNII EUROPEJSKIEJ,\n\nuwzględniając Traktat o funkcjonowaniu Unii Europejskiej, w szczególności jego art. 16,\n\nuwzględniając wniosek Komisji Europejskiej,\n\npo przekazaniu projektu aktu ustawodawczego parlamentom narodowym,\n\nuwzględniając opinię Europejskiego Komitetu Ekonomiczno-Społecznego (1),\n\nuwzględniając opinię Komitetu Regionów (2),\n\nstanowiąc zgodnie ze zwykłą procedurą ustawodawczą (3),\n\na także mając na uwadze, co następuje:\n\n(1)\n\nOchrona osób fizycznych w związku z przetwarzaniem danych osobowych jest jednym z praw podstawowych', 'Art. 8 ust. 1 Karty praw podstawowych Unii Europejskiej (zwanej dalej „Kartą praw podstawowych”) oraz art. 16 ust. 1 Traktatu o funkcjonowaniu Unii Europejskiej (TFUE) stanowią, że każda osoba ma prawo do ochrony danych osobowych jej dotyczących', '(2)\n\nZasady i przepisy dotyczące ochrony osób fizycznych w związku z przetwarzaniem ich danych osobowych nie mogą – niezależnie od obywatelstwa czy miejsca zamieszkania takich osób – naruszać ich podstawowych praw i wolności, w szczególności prawa do ochrony danych osobowych', 'Niniejsze rozporządzenie ma na celu przyczyniać się do tworzenia przestrzeni wolności, bezpieczeństwa i sprawiedliwości oraz unii gospodarczej, do postępu społeczno-gospodarczego, do wzmacniania i konwergencji gospodarek na rynku wewnętrznym, a także do pomyślności ludzi', '(3)\n\nCelem dyrektywy Parlamentu Europejskiego i Rady 95/46/WE (4) jest zharmonizowanie ochrony podstawowych praw i wolności osób fizycznych w związku z czynnościami przetwarzania oraz zapewnienie swobodnego przepływu danych osobowych między państwami członkowskimi.'];
        expect(joinIfNextIsLowerCase(['ROZPORZĄDZENIE PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679\n\nz dnia 27 kwietnia 2016 r', 'w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych)\n\n(Tekst mający znaczenie dla EOG)\n\nPARLAMENT EUROPEJSKI I RADA UNII EUROPEJSKIEJ,\n\nuwzględniając Traktat o funkcjonowaniu Unii Europejskiej, w szczególności jego art', '16,\n\nuwzględniając wniosek Komisji Europejskiej,\n\npo przekazaniu projektu aktu ustawodawczego parlamentom narodowym,\n\nuwzględniając opinię Europejskiego Komitetu Ekonomiczno-Społecznego (1),\n\nuwzględniając opinię Komitetu Regionów (2),\n\nstanowiąc zgodnie ze zwykłą procedurą ustawodawczą (3),\n\na także mając na uwadze, co następuje:\n\n(1)\n\nOchrona osób fizycznych w związku z przetwarzaniem danych osobowych jest jednym z praw podstawowych', 'Art', '8 ust', '1 Karty praw podstawowych Unii Europejskiej (zwanej dalej „Kartą praw podstawowych”) oraz art', '16 ust', '1 Traktatu o funkcjonowaniu Unii Europejskiej (TFUE) stanowią, że każda osoba ma prawo do ochrony danych osobowych jej dotyczących', '(2)\n\nZasady i przepisy dotyczące ochrony osób fizycznych w związku z przetwarzaniem ich danych osobowych nie mogą – niezależnie od obywatelstwa czy miejsca zamieszkania takich osób – naruszać ich podstawowych praw i wolności, w szczególności prawa do ochrony danych osobowych', 'Niniejsze rozporządzenie ma na celu przyczyniać się do tworzenia przestrzeni wolności, bezpieczeństwa i sprawiedliwości oraz unii gospodarczej, do postępu społeczno-gospodarczego, do wzmacniania i konwergencji gospodarek na rynku wewnętrznym, a także do pomyślności ludzi', '(3)\n\nCelem dyrektywy Parlamentu Europejskiego i Rady 95/46/WE (4) jest zharmonizowanie ochrony podstawowych praw i wolności osób fizycznych w związku z czynnościami przetwarzania oraz zapewnienie swobodnego przepływu danych osobowych między państwami członkowskimi.'])).toEqual(joined);
    });
    test('long English array', () => {
        const joined = ['REGULATION (EU) 2016/679 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) (Text with EEA relevance) THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION, Having regard to the Treaty on the Functioning of the European Union, and in particular Article 16 thereof, Having regard to the proposal from the European Commission, After transmission of the draft legislative act to the national parliaments, Having regard to the opinion of the European Economic and Social Committee (1), Having regard to the opinion of the Committee of the Regions (2), Acting in accordance with the ordinary legislative procedure (3), Whereas: (1) The protection of natural persons in relation to the processing of personal data is a fundamental right', 'Article 8(1) of the Charter of Fundamental Rights of the European Union (the ‘Charter’) and Article 16(1) of the Treaty on the Functioning of the European Union (TFEU) provide that everyone has the right to the protection of personal data concerning him or her'];
        expect(joinIfNextIsLowerCase(['REGULATION (EU) 2016/679 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) (Text with EEA relevance) THE EUROPEAN PARLIAMENT AND THE COUNCIL OF THE EUROPEAN UNION, Having regard to the Treaty on the Functioning of the European Union, and in particular Article 16 thereof, Having regard to the proposal from the European Commission, After transmission of the draft legislative act to the national parliaments, Having regard to the opinion of the European Economic and Social Committee (1), Having regard to the opinion of the Committee of the Regions (2), Acting in accordance with the ordinary legislative procedure (3), Whereas: (1) The protection of natural persons in relation to the processing of personal data is a fundamental right', 'Article 8(1) of the Charter of Fundamental Rights of the European Union (the ‘Charter’) and Article 16(1) of the Treaty on the Functioning of the European Union (TFEU) provide that everyone has the right to the protection of personal data concerning him or her'])).toEqual(joined);
    });
    test('additional array', () => {
        const joined = ["Pozazobowiązaniami międzynarodowymipaństwa trzeciego lub organizacji międzynarodowej, Komisja powinna brać pod uwagę obowiązki wynikające z udziału państwa trzeciego lub organizacji międzynarodowej w systemach wielostronnych lub regionalnych, w szczególności w odniesieniu do ochrony danych osobowych, a także realizację takich obowiązków", "W szczególności powinna wziąć pod uwagę przystąpienie państwa trzeciego do konwencji Rady Europy z dnia 28 stycznia 1981 r. o ochronie osób w związku z automatycznym przetwarzaniem danych osobowych", "Oceniając stopień ochrony w państwach trzecich lub organizacjach międzynarodowych, Komisja powinna konsultować się z Europejską Radą Ochrony Danych"];
        expect(joinIfNextIsLowerCase(["Pozazobowiązaniami międzynarodowymipaństwa trzeciego lub organizacji międzynarodowej, Komisja powinna brać pod uwagę obowiązki wynikające z udziału państwa trzeciego lub organizacji międzynarodowej w systemach wielostronnych lub regionalnych, w szczególności w odniesieniu do ochrony danych osobowych, a także realizację takich obowiązków","W szczególności powinna wziąć pod uwagę przystąpienie państwa trzeciego do konwencji Rady Europy z dnia 28 stycznia 1981 r", "o ochronie osób w związku z automatycznym przetwarzaniem danych osobowych", "Oceniając stopień ochrony w państwach trzecich lub organizacjach międzynarodowych, Komisja powinna konsultować się z Europejską Radą Ochrony Danych"])).toEqual(joined);
    });
}) 